/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PdmBarcodeScannerController {
        "barcodeTitle"?: string;
        "changeCamera": () => Promise<void>;
        "dismiss": (result?: any) => Promise<void>;
        "holdForScan": (callback: any) => Promise<any>;
        "present": (props?: any, callback?: any) => Promise<any>;
        "scannerMode"?: string;
    }
    interface SsappWindow {
        "appName": string;
        "landingPath": string;
        "params": {[indexer: string]: string,};
        "seed": string;
    }
}
declare global {
    interface HTMLPdmBarcodeScannerControllerElement extends Components.PdmBarcodeScannerController, HTMLStencilElement {
    }
    var HTMLPdmBarcodeScannerControllerElement: {
        prototype: HTMLPdmBarcodeScannerControllerElement;
        new (): HTMLPdmBarcodeScannerControllerElement;
    };
    interface HTMLSsappWindowElement extends Components.SsappWindow, HTMLStencilElement {
    }
    var HTMLSsappWindowElement: {
        prototype: HTMLSsappWindowElement;
        new (): HTMLSsappWindowElement;
    };
    interface HTMLElementTagNameMap {
        "pdm-barcode-scanner-controller": HTMLPdmBarcodeScannerControllerElement;
        "ssapp-window": HTMLSsappWindowElement;
    }
}
declare namespace LocalJSX {
    interface PdmBarcodeScannerController {
        "barcodeTitle"?: string;
        "scannerMode"?: string;
    }
    interface SsappWindow {
        "appName"?: string;
        "landingPath"?: string;
        "onWindowAction"?: (event: CustomEvent<any>) => void;
        "params"?: {[indexer: string]: string,};
        "seed"?: string;
    }
    interface IntrinsicElements {
        "pdm-barcode-scanner-controller": PdmBarcodeScannerController;
        "ssapp-window": SsappWindow;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pdm-barcode-scanner-controller": LocalJSX.PdmBarcodeScannerController & JSXBase.HTMLAttributes<HTMLPdmBarcodeScannerControllerElement>;
            "ssapp-window": LocalJSX.SsappWindow & JSXBase.HTMLAttributes<HTMLSsappWindowElement>;
        }
    }
}
